root: ./docs/book/

structure:
  readme: introduction.md
  summary: toc.md

redirects:
 how-to/customize-docker-builds/use-code-repositories-to-speed-up-docker-build-times.md: how-to/customize-docker-builds/how-to-reuse-builds.md